// Generates llms.txt (index) and llms-full.txt (everything an AI needs, concatenated)
// from ai/ and docs/. Run: npm run build:ai   (a test fails when the committed files are stale)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(resolve(root, p), 'utf8');
const RAW = 'https://raw.githubusercontent.com/yjmtmtk/pixi-effects/main';

const stripFrontmatter = (s) => s.replace(/^---\n[\s\S]*?\n---\n/, '');

export function buildLlms() {
  const llms = `# pixi-effects

> Declarative motion graphics and video for the web. Describe a video as plain objects (text, shapes, images, video, audio, nested compositions, a 2.5D camera, optional three.js), play it in a canvas, export MP4 / WebM / MOV. Built on PixiJS v8, GSAP and mediabunny. Written to be authored by AI: no per-frame code.

Rules that cause most failures (details in the skill and pitfalls):

- Keyframe \`at\` is measured from the start of its own layer (negative = back from the layer's end). A layer's \`at\` and a transition's \`at\` are composition time.
- Layers are hidden, not removed, after their lifespan; z-order is array order (later = on top).
- Angles are degrees; +z is toward the viewer; any number can be an expression such as 'GW/2 - w/2'.
- Anchors: rect/circle/ellipse are centred, text and image are top-left, compositions use pivotX/pivotY.
- Verify by looking: seek with \`await movie.gotoFrame(n, true)\`, check at least 5 timestamps, and read \`window.__logs\` (library warnings are instructions).

## Start here

- **If you are an AI in a chat with no shell and no files** (a browser chat, a preview window): read only [Chat guide](${RAW}/ai/CHAT.md) and copy [chat-template.html](${RAW}/ai/chat-template.html); everything below is for an AI that can run commands.
- [Skill: workflow and rules](${RAW}/skills/pixi-effects/SKILL.md): how to build, check and export a video; read first
- [Cheatsheet](${RAW}/skills/pixi-effects/reference/cheatsheet.md): every layer type, prop, default and convention on one page
- [Recipes](${RAW}/skills/pixi-effects/reference/recipes.md): tested building blocks (kinetic type, lower-third, count-up, bar chart, 2.5D title, camera orbit, slideshow with transitions, sound effects without files, music written as text, three.js, a presentation deck, visuals that follow music)
- [Pitfalls](${RAW}/skills/pixi-effects/reference/pitfalls.md): real mistakes made by AI authors, with fixes
- [Starter template](${RAW}/skills/pixi-effects/template.html): copy this file to begin

## Reference

- [DSL reference](${RAW}/docs/dsl.md): composition, sequences, 3D layers and camera, keyframes, expressions, filters, transitions, presets (wiggle, stagger, animateText, followPath, particles, react, deck), music written as text, stops for presentations
- [API reference](${RAW}/docs/api.md): Movie, Controller, Presenter (presentations, PDF export), audio analysis (audioEnvelope), events, render options, pixi-effects/three
- [README](${RAW}/README.md): install, CDN import map, quickstart

## Optional

- [Everything above in one file](${RAW}/llms-full.txt)
- [Examples and playground](https://yjmtmtk.github.io/pixi-effects/examples/)
`;

  const parts = [
    ['skills/pixi-effects/SKILL.md', stripFrontmatter(read('skills/pixi-effects/SKILL.md'))],
    ['skills/pixi-effects/reference/cheatsheet.md', read('skills/pixi-effects/reference/cheatsheet.md')],
    ['skills/pixi-effects/reference/pitfalls.md', read('skills/pixi-effects/reference/pitfalls.md')],
    ['skills/pixi-effects/reference/recipes.md', read('skills/pixi-effects/reference/recipes.md')],
    ['docs/dsl.md', read('docs/dsl.md')],
    ['docs/api.md', read('docs/api.md')],
  ];
  const full =
    `# pixi-effects — full documentation for AI agents\n\n` +
    `Concatenation of the skill, cheatsheet, pitfalls, recipes and the DSL / API references. Generated by scripts/build-llms.mjs; do not edit.\n\n` +
    parts.map(([name, body]) => `\n\n<!-- ===== ${name} ===== -->\n\n${body.trim()}\n`).join('');
  return { llms, full };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { llms, full } = buildLlms();
  writeFileSync(resolve(root, 'llms.txt'), llms);
  writeFileSync(resolve(root, 'llms-full.txt'), full);
  console.log(`llms.txt (${llms.length} chars), llms-full.txt (${full.length} chars)`);
}
